name: Builds

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config: [Release]
        platform: [Win32, x64]
    
    steps:
    - uses: actions/checkout@v3

    - uses: Trass3r/setup-cpp@master

    - uses: microsoft/setup-msbuild@v1.1.3
      with:
        vs-version: '[17.0,18.0)'

    - uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ matrix.config }}-${{ matrix.platform }}
        max-size: 1G
        verbose: 1

    - name: Build the source code
      run: |
        nuget restore SKIF.sln
        msbuild SKIF.sln -p:Configuration="${{ matrix.config }}" -p:Platform="${{ matrix.platform }}" -m

    - name: Prepare environment variables for the artifact name
      run: |
        $Version = (Get-Item ".\Builds\SKIF*.exe").VersionInfo.ProductVersion
        If ($null -eq $Version) { $Version = "unknown" }
        "SKIF_VERSION=$Version" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append
        "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

    - uses: actions/upload-artifact@v3
      with:
        name: SKIF_${{ env.SKIF_VERSION }}_${{ env.SHORT_SHA }}
        path: |
          Builds/SKIF*.exe
        if-no-files-found: error
