name: Builds

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      #matrix:
      #  config: [Release]
      #  platform: [Win32, x64]
      # Originally the build was then executed with this:
      # msbuild SKIF.sln -p:Configuration="${{ matrix.config }}" -p:Platform="${{ matrix.platform }}" -m
    
    steps:
    - uses: actions/checkout@v3

    - uses: SpecialKO/GA-setup-cpp@master

    - uses: microsoft/setup-msbuild@v1.1.3
      with:
        vs-version: '[17.0,18.0)'

    - name: Restore the required Nuget packages
      run: |
        nuget restore SKIF.sln

    - name: Build the codebase (64-bit)
      run: |
        msbuild SKIF.sln -p:Configuration="Release" -p:Platform="x64" -m

    - name: Build the codebase (32-bit)
      run: |
        msbuild SKIF.sln -p:Configuration="Release" -p:Platform="Win32" -m

    - name: Prepare environment variables for the artifact name
      run: |
        $Version = (Get-Item ".\Builds\SKIF*.exe").VersionInfo.ProductVersion | Select-Object -First 1
        If ($null -eq $Version) { $Version = "unknown" }
        "SKIF_VERSION=$Version" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append
        "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

    - uses: actions/upload-artifact@v3
      with:
        name: SKIF_${{ env.SKIF_VERSION }}_${{ env.SHORT_SHA }}
        path: |
          Builds/SKIF*.exe
        if-no-files-found: error

    - uses: actions/upload-artifact@v3
      with:
        name: SKIF_${{ env.SKIF_VERSION }}_${{ env.SHORT_SHA }}_debug_symbols
        path: |
          Builds/SKIF*.pdb
        if-no-files-found: warn
